<a href="https://colab.research.google.com/github/shivanand22cs043/shivu/blob/main/week_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1, 4, 5, 8], float)
print(type(a))
a

<class 'numpy.ndarray'>


array([1., 4., 5., 8.])

In [ ]:
a[:2]
print(a[1:3])

[4. 5.]


In [ ]:
a[0] = 5.
a

array([5., 4., 5., 8.])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)

print(a[0,0])
print(a[0,1])
a

1.0
2.0


array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
#print(a[1,0:2])
print(a[1,1])
print(a[:,2])

print(a[-1:,-1:])

5.0
[3. 6.]
[[6.]]


In [ ]:
a.shape

(2, 3)

In [ ]:
a.dtype

dtype('float64')

In [ ]:
len(a)

2

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(2 in a)
print(0 in a)

True
False


In [ ]:
a = np.array(range(10), float)
print(a)
b = a.reshape((5, 2))
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [ ]:
a = np.array([1, 2, 3], float)
print(a.tolist())
print(list(a))

[1.0, 2.0, 3.0]
[1.0, 2.0, 3.0]


In [ ]:
a = np.array([1, 2, 3], float)
s = a.tobytes()
print(s)
print(np.frombuffer(s))

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'
[1. 2. 3.]


In [ ]:
a = np.array(range(6), float).reshape((2, 3))
print(a)
a.transpose()

[[0. 1. 2.]
 [3. 4. 5.]]


array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [ ]:
a = np.array([1,2], int)
b = np.array([3,4,5,6], float)
c = np.array([1,8,9], int)
np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 1., 8., 9.])

In [ ]:

import numpy as np
arr = np.array([1,2,3,4,5])
print("array with rank 1: \n",arr)

arr= np.array([[1,2,3],
               [4,5,6]])
print("array with rank 2: \n",arr)

arr = np.array((1,3,2))
print("array created using passed tuple: \n",arr)

array with rank 1: 
 [1 2 3 4 5]
array with rank 2: 
 [[1 2 3]
 [4 5 6]]
array created using passed tuple: 
 [1 3 2]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print("a:",a)
sum=np.sum(a)
print("sum:",sum)

a: [1 2 3 4 5]
sum: 15


In [ ]:
x=np.array([[1,2,3],[4,5,6]])
np.prod(x)

720

In [ ]:
import numpy as np
a=np.array([1,2,3,4,10])
print("a:",a)
avg=np.average(a)
print("average:",avg)

a: [ 1  2  3  4 10]
average: 4.0


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print("Array a:",a)

mean=np.mean(a)
print("mean:",mean)

Array a: [1 2 3 4 5]
mean: 3.0


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print("Array a:",a)

minimum=np.min(a)
print("minimum:",minimum)

Array a: [1 2 3 4 5]
minimum: 1


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print("Array a:",a)

maximum=np.max(a)
print("maximum:",maximum)

Array a: [1 2 3 4 5]
maximum: 5


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print("Array a:",a)

standard_deviation=np.std(a)
print("standard deviation:",standard_deviation)

Array a: [1 2 3 4 5]
standard deviation: 1.4142135623730951


In [ ]:
import numpy as np
import timeit

print(np.sum(np.arange(4)))

print("time taken by vectorized sum:",end="")
%timeit np.sum(np.arange(4))

total=0
for item in range(0,4):
  total +=item
a=total
print("\n"+str(a))

print("time taken by iterative sum:",end="")
%timeit a

6
time taken by vectorized sum:15.1 µs ± 3.68 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

6
time taken by iterative sum:29.9 ns ± 0.806 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [ ]:
import numpy as np
np.num=[3,2,1,4]
np.num1=[1,2,3,4]
print("production operation using vectorization:",np.prod(np.num))
print("square root operation using vectorization:",np.sqrt(np.num[3]))
print("module operation using vectorization:",np.mod(np.num,np.num1))
print("mean operation using vectorization:",np.mean(np.num))
print("median operation using vectorization:",np.median(np.num))
print("minimum operation using vectorization:",np.min(np.num))
print("maximum operation using vectorization:",np.max(np.num))

production operation using vectorization: 24
square root operation using vectorization: 2.0
module operation using vectorization: [0 0 1 0]
mean operation using vectorization: 2.5
median operation using vectorization: 2.5
minimum operation using vectorization: 1
maximum operation using vectorization: 4


In [ ]:
x = lambda a : a + 1
print(x(5))

6


In [ ]:
x = lambda a, b, c : a + b + c
print(x(5, 6, 2))

13


In [ ]:
lst = [1,2,3.4,5]
print(list(map(lambda x:x*10,lst)))

[10, 20, 34.0, 50]


In [ ]:
from functools import reduce
lst = [1,2,3,4,5]
print(reduce(lambda x,y:x+y,lst))


15


In [ ]:
import numpy as np
from operator import add
from functools import reduce

np.num=[2,3,6,9,10]
sq=list(map(lambda square: (square ** 2),np.num))
print("using map function",sq)

even=list(filter(lambda x:x%2==0,np.num))
print("using filter function",even)

re=reduce(add,np.num)
print("using reduce function",re)

using map function [4, 9, 36, 81, 100]
using filter function [2, 6, 10]
using reduce function 30


In [ ]:
lst=[53,3,22,2,11,31]
print(list(filter(lambda x:x>10,lst)))

[53, 22, 11, 31]


In [ ]:
import pandas as pd
ds1=pd.Series([2,4,8,10])
ds2=pd.Series([1,3,7,9])
print("multiplytwo series:")
ds=ds1*ds2
print(ds)
print("divided Series1 by Series2:")
ds=ds1/ds2
print(ds)

multiplytwo series:
0     2
1    12
2    56
3    90
dtype: int64
divided Series1 by Series2:
0    2.000000
1    1.333333
2    1.142857
3    1.111111
dtype: float64


In [ ]:
import pandas as pd
d1={'a':100,'b':200,'c':300}
print("original dictionary")
print(d1)
new_series=pd.Series(d1)
print("converted series")
print(new_series)

original dictionary
{'a': 100, 'b': 200, 'c': 300}
converted series
a    100
b    200
c    300
dtype: int64


In [ ]:
import pandas as pd
s=pd.Series([400,300.12,100,200])
print("original series")
print(s)
new_s=pd.Series(s).sort_values()
print(new_s)

original series
0    400.00
1    300.12
2    100.00
3    200.00
dtype: float64
2    100.00
3    200.00
1    300.12
0    400.00
dtype: float64


In [ ]:
import pandas as pd
s=pd.Series(data=[1,2,3],index=['A','B','C'])
print("original series")
print(s)
s=s.reindex(index=['B','A','C'])
print("Data series after changing the order of index:")
print(s)

original series
A    1
B    2
C    3
dtype: int64
Data series after changing the order of index:
B    2
A    1
C    3
dtype: int64


In [ ]:
import pandas as pd
import numpy as np
sr1=pd.Series([1,2,3])
sr2=pd.Series([2,3,6])
print("original Series:")
print("sr1")
print(sr1)
print("sr2")
print(sr2)
print("\nitems of a given serires not present in another given series:")
sr11=pd.Series(np.union1d(sr1,sr2))
sr12=pd.Series(np.intersect1d(sr1,sr2))
result=sr11[~sr11.isin(sr12)]
print(result)

original Series:
sr1
0    1
1    2
2    3
dtype: int64
sr2
0    2
1    3
2    6
dtype: int64

items of a given serires not present in another given series:
0    1
3    6
dtype: int64


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj'],
'score': [12.5, 9]}
labels = ['NAME', 'SCORE']
df = pd.DataFrame(exam_data , index=labels)
print(df)

         name  score
NAME   Manish   12.5
SCORE  Dhiraj    9.0


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,2.5, 9]}
df = pd.DataFrame(exam_data )
print("First three rows of the data frame:")
print(df.iloc[:3])

First three rows of the data frame:
     name  score
0  Manish   12.5
1  Dhiraj   91.0
2     Man    2.5


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,2.5, 9]}
df = pd.DataFrame(exam_data )
total_rows=len(df.axes[0])
total_cols=len(df.axes[1])
print("Number of Rows: "+str(total_rows))
print("Number of Columns: "+str(total_cols))

Number of Rows: 4
Number of Columns: 2


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
print("Rows where score between 15 and 20 (inclusive):")
print(df[df['score'].between(15, 20)])

Rows where score between 15 and 20 (inclusive):
   name  score
3  Dhir   19.0


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
result_sort=df.sort_values(by=['name', 'score'], ascending=[True, True])
print("Sort the data frame first by ‘name’ in descending order, then by ‘score’ in ascending order:")
print(result_sort)

Sort the data frame first by ‘name’ in descending order, then by ‘score’ in ascending order:
     name  score
3    Dhir   19.0
1  Dhiraj   91.0
2     Man   20.5
0  Manish   12.5


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
df['name'] = df['name'].replace('Manish', 'Anish')
print(df)


     name  score
0   Anish   12.5
1  Dhiraj   91.0
2     Man   20.5
3    Dhir   19.0


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
medium = ['english','hindi','hindi','english']
df['medium'] = medium
print("\nNew DataFrame after inserting the 'medium' column")
print(df)


New DataFrame after inserting the 'medium' column
     name  score   medium
0  Manish   12.5  english
1  Dhiraj   91.0    hindi
2     Man   20.5    hindi
3    Dhir   19.0  english


In [ ]:
import numpy as np
exam_data = {'name': ['sagar', 'rahul','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
df = df.rename(columns={'name': 'NAME', 'score': 'SCORE'})
print("New DataFrame after renaming columns:")
print(df)

New DataFrame after renaming columns:
    NAME  SCORE
0  sagar   12.5
1  rahul   91.0
2    Man   20.5
3   Dhir   19.0


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['rahim', 'venki','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
df = df[df.score >= 20]
print("New DataFrame")
print(df)

New DataFrame
    name  score
1  venki   91.0
2    Man   20.5


In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
print("Data Series:")
print(s1)
print(s2)
df = pd.concat([s1, s2], axis=1)
print("New DataFrame combining two series:")
print(df)

Data Series:
0    100
1    200
2    400
dtype: object
0    10
1    20
2    40
dtype: object
New DataFrame combining two series:
     0   1
0  100  10
1  200  20
2  400  40


In [ ]:
import pandas as pd
import numpy as nps1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
df = pd.concat([s1, s2], axis=1)
print("Value of Row4")
print(df.iloc[2])

Value of Row4
0    400
1     40
Name: 2, dtype: object


In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
df = pd.concat([s1, s2], axis=1)
new_col = [1, 2, 3]
idx = 0
df.insert(loc=idx, column='1', value=new_col)
print("\nNew DataFrame")
print(df)


New DataFrame
   1    0   1
0  1  100  10
1  2  200  20
2  3  400  40
